[tool.poetry]
name = "sudoku"
version = "0.1.0"
description = ""
authors = ["Olaf Gladis <github@gladis.org>"]

[tool.poetry.dependencies]
python = "^3.8"
pydantic = "^1.6.1"
pygame = "^2.0.2.dev3"
wrapt = "^1.12.1"
myst-parser = {git = "https://github.com/executablebooks/MyST-Parser.git"}

[tool.poetry.dev-dependencies]
pytest = "^6.1.0"
furo = "*"
commonmark = "^0.9.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
